## 프로젝트 기반 빅데이터 서비스 솔루션 개발 전문 과정

#### 교과목명 : 모델 성능 평가
- 평가일 : 03.13
- 성명 :이재호
- 점수 :70(7/10)

Q1. iris data를 불러와서 붓꽃의 종류를 분류하는 모델링을 수행한 후 오차행렬과 정확도를 평가하세요.
- test_size = 0.2, 분류기는 DecisionTreeClassifier를 이용

In [1]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [2]:
df= pd.DataFrame(iris.data, columns=iris.feature_names)
df['class'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   class  
0      0  
1      0  
2      0  
3      0  
4      0

In [5]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score,recall_score,f1_score,roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

X_train,X_test,y_train,y_test = train_test_split(iris.data, iris.target,test_size=0.2, random_state=10)
dt_clf = DecisionTreeClassifier()
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)

confusion = confusion_matrix(y_test,pred)
accuracy = accuracy_score(y_test,pred)

print(confusion)
print(accuracy)

[[10  0  0]
 [ 0 12  1]
 [ 0  0  7]]
0.9666666666666667


Q2. 타이타닉 분석용 데이터세트인 tdf1.pkl를 불러와서 생존자 예측 모델을 만든 후 오차행렬, 정확도, 재현율, f1, AUC를 포함하는 사용자 함수를 활용하여 평가하세요.
- test_size = 0.2, 분류기는 RandomForestClassifier 이용

In [6]:
import pandas as pd
tdf = pd.read_pickle('datasets/tdf1.pkl')
tdf.head()

Survived  Sex  Town_0  Town_1  Town_2  Family_Big  Family_Single  \
0         0    1       0       0       1           0              0   
1         1    0       1       0       0           0              0   
2         1    0       0       0       1           0              1   
3         1    0       0       0       1           0              0   
4         0    1       0       0       1           0              1   

   Family_Small  Age_10s  Age_20s  Age_30s  Age_40s  Age_50s  Age_Elderly  \
0             1        0        0        1        0        0            0   
1             1        0        0        0        1        0            0   
2             0        0        0        1        0        0            0   
3             1        0        0        0        1        0            0   
4             0        0        0        0        1        0            0   

  Fare_cat  
0        1  
1        4  
2        1  
3        4  
4        2

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score,recall_score,f1_score,roc_auc_score
def get_clf_eval(y_test, pred, pred_proba):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test,pred)
    precision=precision_score(y_test,pred)
    recall = recall_score(y_test, pred)
    f1 = f1_score(y_test, pred)
    auc = roc_auc_score(y_test, pred_proba)
    
    print('오차행렬:\n', confusion)
    print('정확도: {:.4f}, 정밀도: {:.4f}, 재현율: {:.4f}, f1: {:.4f}, AUC: {:.4f}'.format(accuracy, precision, recall, f1, auc)) 

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X = tdf.drop('Survived',axis=1)
y = tdf['Survived']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=10)
rf_clf = RandomForestClassifier()
rf_clf.fit(X_train,y_train)
rf_pred = rf_clf.predict(X_test)
rf_pred_proba = rf_clf.predict_proba(X_test)[:,1]

get_clf_eval(y_test,rf_pred,rf_pred_proba)

오차행렬:
 [[102  15]
 [ 14  48]]
정확도: 0.8380, 정밀도: 0.7619, 재현율: 0.7742, f1: 0.7680, AUC: 0.8763


Q3. Q2에서 생성한 모델로 교차검증(cv=5)을 수행하고 평균 정확도를 출력하세요.

In [12]:
import numpy as np
from sklearn.model_selection import cross_val_score
scores = cross_val_score(rf_clf,X,y,scoring='accuracy', cv=5)
print('정확도:',np.round(scores,4))
print('평균 정확도:',round(np.mean(scores),4))

정확도: [0.7877 0.8034 0.7697 0.7697 0.8258]
평균 정확도: 0.7912


Q4. Q2에서 생성한 예측모델에 대하여 교차 검증 및 성능 개선을 수행하세요.(GridSearchCV 활용)

In [15]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import GridSearchCV
params = {'n_estimators':[50,100,200],
         'max_depth':[2, 4, 6, 8, 10],
         'min_samples_leaf':[2,8,14,20],
         'min_samples_split':[2,8.14,20]}
rf_dclf = GridSearchCV(rf_clf, param_grid=params, cv=5, refit=True)
rf_dclf.fit(X_train,y_train)
print(rf_dclf)
print('최적 하이퍼파라미터:',rf_dclf.best_params_)
print('최고 정확도:', rf_dclf.best_score_)
best_rclf = rf_dclf.best_estimator_
print(best_rclf)
rclf_pred = best_rclf.predict(X_test)
rclf_pred_proba = best_rclf.predict_proba(X_test)[:,1]
get_clf_eval(y_test, rclf_pred, rclf_pred_proba)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [2, 4, 6, 8, 10],
                         'min_samples_leaf': [2, 8, 14, 20],
                         'min_samples_split': [2, 8.14, 20],
                         'n_estimators': [50, 100, 200]})
최적 하이퍼파라미터: {'max_depth': 4, 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 100}
최고 정확도: 0.8202107751403528
RandomForestClassifier(max_depth=4, min_samples_leaf=2)
오차행렬:
 [[107  10]
 [ 19  43]]
정확도: 0.8380, 정밀도: 0.8113, 재현율: 0.6935, f1: 0.7478, AUC: 0.8606


Q5 ~ Q7. 'dataset/diabetes.csv'을 불러와서 아래사항을 수행하세요.
- 피마 인디언 당뇨병 예측을 로지스틱 회귀를 이용하여 수행하고 사용자 함수를 작성하여 평가(오차행렬, 정확도, 정밀도, 재현율, F1, ROC_AUC)
- 임곗값을 0.3에서 0.5까지 변화시키면서 정밀도와 재현율이 조정되는 과정을 시각화 
- 재현율 기준의 성능을 개선하기 위하여 그 값이 0이 될 수 없는 각 칼럼을 탐색하여 적절한 처리를 한 후 로지스틱 회귀로 예측 및 평가 수행(오차행렬, 정확도, 정밀도, 재현율, F1, ROC_AUC)


Q8. "dataset/auto-mpg.xlsx"을 불러와서 회귀 모델을 생성하고 MSE, RMSE, R2로 평가를 수행하세요.

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df = pd.read_excel('./datasets/auto-mpg1.xlsx')
ndf = df[['mpg','cylinders','horsepower','weight']]
ndf.head()

mpg  cylinders horsepower  weight
0  18.0          8        130    3504
1  15.0          8        165    3693
2  18.0          8        150    3436
3  16.0          8        150    3433
4  17.0          8        140    3449

In [23]:
ndf.horsepower.replace("?",np.nan, inplace=True)
ndf.dropna(subset=['horsepower'],axis=0, inplace=True)
ndf['horsepower'] = ndf['horsepower'].astype('float')
ndf.to_pickle('./datasets/auto-mpg1.pkl')
ndf = pd.read_pickle('./datasets/auto-mpg1.pkl')
ndf.head()

mpg  cylinders  horsepower  weight
0  18.0          8       130.0    3504
1  15.0          8       165.0    3693
2  18.0          8       150.0    3436
3  16.0          8       150.0    3433
4  17.0          8       140.0    3449

In [25]:
X = ndf[['weight']]
y = ndf['mpg']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,
                                                y,
                                                test_size=0.3,
                                                random_state=11)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

lr = LinearRegression()
lr.fit(X_train,y_train)
y_preds = lr.predict(X_test)
mse = mean_squared_error(y_test, y_preds)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_preds)
print('MSE:{0:.4f}, RMSE:{1:.4f}, R2:{2:.4f}'.format(mse,rmse,r2))

MSE:22.1690, RMSE:4.7084, R2:0.6411


Q9. 'load_boston' 을 불러와서 cross_val_score를 이용한 cv=5인 교차검증을 수행 후 MSE, RMSE를 출력하세요.(LineaRegression) 

In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_boston

house = load_boston()
house.keys()

house_df = pd.DataFrame(house.data, columns = house.feature_names)
house_df['PRICE'] = house.target

house_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [27]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

from sklearn.model_selection import cross_val_score

y_target = house_df['PRICE']
X_data = house_df.drop(['PRICE'], axis=1, inplace=False)
lr = LinearRegression()

neg_mse_scores = cross_val_score(lr,X_data, y_target,\
                                scoring="neg_mean_squared_error",cv=5)
rmse_scores = np.sqrt(-1*neg_mse_scores)
avg_rmse = np.mean(rmse_scores)

print('5 folds의 개별 Negative MSE scores: ', np.round(neg_mse_scores,2))
print('5 folds의 개별 RMSE scores: ', np.round(rmse_scores, 2))
print('5 folds의 평균 RMSE : {:.3f}'.format(avg_rmse))

5 folds의 개별 Negative MSE scores:  [-12.46 -26.05 -33.07 -80.76 -33.31]
5 folds의 개별 RMSE scores:  [3.53 5.1  5.75 8.99 5.77]
5 folds의 평균 RMSE : 5.829


Q10. 'Q9에 대하여 R2 Score를 구하세요.(k=5) 

In [28]:
from sklearn.model_selection import KFold
lr = LinearRegression()
cv = KFold(5, shuffle=True, random_state=0)
r2_scores = cross_val_score(lr,X_data, y_target, scoring="r2",cv=cv)
r2_score = np.mean(r2_scores)

print(f"각 fold 별 결정계수: {np.round(r2_scores,3)}")
print(f"평균 결정 계수: {r2_score:.3f}")

각 fold 별 결정계수: [0.589 0.778 0.668 0.668 0.84 ]
평균 결정 계수: 0.709
