http://matrix.skku.ac.kr/math4AI-tools/cosine_similarity/

cos = b/a  
b = acos


In [1]:
import numpy as np
def cos_similarity(v1,v2):
    dot_product = np.dot(v1,v2)
    l2_norm = (np.sqrt(sum(np.square(v1))) * np.sqrt(sum(np.square(v2))))
    similarity = dot_product / l2_norm
    
    return similarity

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

doc_list = ['if you take the blue pill, the story ends' ,
            'if you take the red pill, you stay in Wonderland',
            'if you take the red pill, I show you how deep the rabbit hole goes']
tfidf_vect_simple = TfidfVectorizer()
feature_vect_simple = tfidf_vect_simple.fit_transform(doc_list)
print(feature_vect_simple.shape)

(3, 18)


In [3]:
# 밀집행렬로 변환
feature_vect_dense = feature_vect_simple.todense()

# 첫번째 문장과 두번째 문장의 벡터 추출
vect1 = np.array(feature_vect_dense[0]).reshape(-1,)
vect2 =  np.array(feature_vect_dense[1]).reshape(-1,)

similarity_simple = cos_similarity(vect1,vect2)
print(f'코사인 유사도:{similarity_simple:.4f}')

코사인 유사도:0.4021


In [6]:
from sklearn.metrics.pairwise import cosine_similarity
sim_pair = cosine_similarity (feature_vect_simple[0], feature_vect_simple)
sim_pair

array([[1.        , 0.40207758, 0.40425045]])

In [7]:
from sklearn.metrics.pairwise import cosine_similarity
sim_pair = cosine_similarity (feature_vect_simple[0], feature_vect_simple[1:])
sim_pair

array([[0.40207758, 0.40425045]])

In [8]:
from sklearn.metrics.pairwise import cosine_similarity
sim_pair2 = cosine_similarity (feature_vect_simple, feature_vect_simple)
sim_pair2

array([[1.        , 0.40207758, 0.40425045],
       [0.40207758, 1.        , 0.45647296],
       [0.40425045, 0.45647296, 1.        ]])

[과제] Opinion Review 데이터 셋을이용한 문서 유사도를 측정하세요