Numpy는 "Numerical Python"의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공

- Numerical Python을 의미하는 Numpy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들수있도록 지원하는 대표적인 패키지
- 많은 머신러닝 알고리즘이 넘파이 기반으로 작성되어 있으며 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함
- 넘파이의 기본 데이터 타입은 ndarray.nd.array를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행

Numpy 특징
- 강력한 N차원 배열 객체
- 정교한 브로드케스팅 기능
- 유용한 선형 대수학, 푸리에 변환 및 난수 기능
- 푸리에 변환은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로분해하는 변환
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

In [1]:
!pip install numpy

In [3]:
import numpy as np
z = np.arange(10)
print(z,type(z))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [6]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [7]:
%time for _ in range(10): my_array2 = my_arr * 2

Wall time: 12.9 ms


In [8]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 591 ms


In [10]:
# 배열 연산
#np.random.randn 가우시안 표준 정규분표에서 난수 매트릭스 array생성
data = np.random.randn(2,3)  # 표준 정규 분포로 구성되는 2행 3열 매트릭스
print(data,'\n')
print(data * 10, '\n')
print(data + data)


[[-1.78247473  0.08727414 -0.03022014]
 [-1.13613818 -1.34393733 -0.85311017]] 

[[-17.82474733   0.87274143  -0.30220136]
 [-11.3613818  -13.43937333  -8.53110174]] 

[[-3.56494947  0.17454829 -0.06044027]
 [-2.27227636 -2.68787467 -1.70622035]]


In [11]:
print(data.shape) # 크기
print(data.dtype) #데이터 타입
print(data.ndim) # 차원

(2, 3)
float64
2


다차원 배열
<img src = 'numpy차원.jpg' STYLE='width:300px;'>

In [15]:
data2 = [[1,2,3,4],[5,6,7,8]]
print(type(data2),'\n')
arr2 = np.array(data2)
print(arr2, type(arr2))

<class 'list'> 

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [16]:
print(arr2.ndim,'\n')
print(arr2.shape)

2 

(2, 4)


In [19]:
# 1차원 배열로 3개의 데이터
array1 = np.array([1,2,3])
print(array1,type(array1),array1.shape) #(,열)이 아닌(열,)형태로 출력


[1 2 3] <class 'numpy.ndarray'> (3,)


In [ ]:
# 2차원 배열로 2개의 row와 3개의 column으로 구성된 6개의 데이터

In [28]:
array2 = np.array([[1,2,3],[2,3,4]])
print(array2,type(array2),array2.shape)

[[1 2 3]
 [2 3 4]] <class 'numpy.ndarray'> (2, 3)


In [23]:
array2 = np.array([1,2,3,4,5,6])
print(array2,type(array2),array2.ndim,'\n')

[1 2 3 4 5 6] <class 'numpy.ndarray'> 1 



In [ ]:
# 1개의 row와 3개의 colimn으로 구성된 2차원 배열

In [29]:
array21 = np.array([[1,2,3]])     #2차원으로 할시 []추가된다.
print(array21,array21.shape)

[[1 2 3]] (1, 3)


In [31]:
# 3차원 
array3 = np.array([[[1,2,3,]]])
print(array3,array3.shape)

[[[1 2 3]]] (1, 1, 3)


In [33]:
array4 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],
                  [[1,2,3,4,5],[6,7,8,9,10]],
                  [[1,2,3,4,5],[6,7,8,9,10]]])
print(array4,array4.shape,'\n')
print(type(array4))

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]] (3, 2, 5) 

<class 'numpy.ndarray'>


In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# 경고 메시지 제외 처리
import warnings
warnings.filterwarning('igonore')

배열 생성 및 초기화
- Numpy는 원하는 shape로 배열을 설정하고 각 요소를 특정값으로 초기화하는 zeros,ones,full,eye 함수 제공
- 피라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like,full_like 함수도 제공


In [34]:
print(np.zeros(10),'\n')
print(np.zeros((3,6)),'\n')
print(np.zeros((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [35]:
print(np.ones((2,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [36]:
ar1 = np.full((2,2),5)
ar1

array([[5, 5],
       [5, 5]])

In [37]:
# 항등행렬, 단위행렬 
ar2 = np.eye(3)
ar2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# [과제] 
 # zeros_like, ones_like,full_like 함수 사용 예

In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print()

ar1 = np.zeros_like(a)
ar2 = ar1.astype(float)
print(ar2, ar2.dtype)
print()

ar3 = np.ones_like(a)
ar4 = ar3.astype(float)
print(ar4, ar4.dtype)
print()

ar5 = np.full_like(a, 6)
ar6 = ar5.astype('float32')
print(ar6, ar6.dtype)
print()


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] float64

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]] float32



In [208]:
import numpy as np

a = np.zeros((2,2), dtype=int)
b = [1, 2, 3, 4, 5]
c = np.zeros_like(b, dtype=int)

print(a)
print(b)
print(c)

[[0 0]
 [0 0]]
[1, 2, 3, 4, 5]
[0 0 0 0 0]


In [209]:
a = np.array([1,4,3,7,9])
b = np.array([[1,6,7],[4,5,3]])

np.zeros_like(a)

np.ones_like(b)

array([[1, 1, 1],
       [1, 1, 1]])

In [210]:
import numpy as np

a = np.arange(5, dtype=int)
a_full_like = np.full_like(a, 1)
print(a)
print(a_full_like)

[0 1 2 3 4]
[1 1 1 1 1]


In [38]:
# arange 함수 : Python의 range함수의 배열 버전
arr1 = np.arange(15)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
arr2 = range(15)
arr2

range(0, 15)

In [44]:
arr2 = arr1.reshape(3,5)
print(arr2,arr2.shape,'\n')
arr3 = arr1.reshape(1,3,5)
print(arr3,arr3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]] (1, 3, 5)


In [ ]:
# array1에 reshape함수를 이용, (5,2) 배열을 생성하고 크기를 같이 출력하세요

In [49]:
array1= np.arange(10)
array2 = array1.reshape(5,2)
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
#0~29 일차원 배열을 생성한 후 일차원 배열을 다시  2,3차원 배열을  생성하세요

In [52]:
array1= np.arange(30)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [54]:
array1 = np.arange(30)
array2 = array1.reshape(5,6)
print(array2,array2.shape,'\n')
array3 = array2.reshape(1,5,6)
print(array3,array3.shape)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] (5, 6) 

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]]] (1, 5, 6)


In [60]:
# reshape(-1,-1)이용,차원 변경
array1 = np.arange(30)
ar12 = array1.reshape(3,-1)
print(ar12,ar12.shape,'\n')
ar13 = array1.reshape(-1,2,5)
print(ar13,ar13.shape,'\n')

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] (3, 10) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5) 



In [63]:
# 2 -> 1, 3차원으로 변환
ar12



NameError: name 'array12' is not defined

In [66]:
ar1=ar12.reshape(-1,)
ar3=ar12.reshape(-1,2,5)
print(ar1,ar1.shape,'\n')
print(ar3,ar3.shape,'\n')


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] (30,) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5) 



In [67]:
# 3 -> 1,2차원으로  변환하여 출력
ar3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [70]:
ar1=ar3.reshape(-1,)
ar2=ar3.reshape(-1,5)
print(ar1,ar1.shape,'\n')
print(ar2,ar2.shape,'\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] (30,) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]] (6, 5) 



In [69]:
ar1=ar3.reshape(-1,)
ar2=ar3.reshape(-1,3)
print(ar1,ar1.shape,'\n')
print(ar2,ar2.shape,'\n')


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] (30,) 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]] (10, 3) 



행렬의 종류
- 정방행렬은 행과 열의 수가 같은 행렬
- 대각행렬은 주대각선 원소를 제외한 모든 원소들이 0인 정방행렬
- 항등행렬은 행렬 곱셈 연산에 항등원으로 작용하는 행렬
- 영행렬은 모든 원소가 0인 행렬로 곱셈 연산에서 영원으로 작용하는 행렬
- 전치행렬은 주대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
- 직교행렬은 행렬 A의 역행렬이 A의 전치행렬이고 A의 전치행렬과 A 행렬을 곱하였을때 항등행렬이 나오는 행렬

In [71]:
# 정방행렬
ar1 = np.full((3,3),7)
ar1

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [72]:
# 항등행렬,단위행렬
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
# 영행렬
a = np.zeros(25)
a.reshape(5,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

ndarry 데이터 형태 지정 및 변경
<img src = '데이터형태.jpg' STYLE='width:300px;'>

In [81]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)
print(arr1,arr1.dtype,'\n')
print(arr2.dtype)

[1. 2. 3.] float64 

int32


In [85]:
# 타입 변경
arr = np.array([1,2,3,4,5,])
print(arr.dtype)

float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [87]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [89]:
# empty 함수 : shape 와 dtype을 입력 받아 초기화되지 않는 배열을 만들어준다. cf.zeros 함수
# empty 함수를 실행할 때마다 값이 다른것을 확인할수 있다.이는 해당 메모리 영역에 어떤 데이터가 남아있었던지 상관없이
# 그대로 영역의 주소만 알려줄 뿐 초기화는 사용자에게 맡기기 때문임.
print(np.empty(shape=(10,),dtype=np.int8))
print(np.zeros(shape=(10,),dtype=np.int8))

[1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0]


In [94]:
# 문자열 타입으로 배열 만들기
# arr = np.array([1,2,3,4], dtype='S')
arr = np.array([1,2,3,4], dtype=np.string_)
print(arr,arr.dtype)

[b'1' b'2' b'3' b'4'] |S1


In [95]:
arr1 = arr.astype('float')
print(arr1,arr1.dtype)

[1. 2. 3. 4.] float64


In [ ]:
# 정수와 실수로 구성된 list_e = [1.2,2.3,3]을 numpy를 이용해서 실수형과 정수형으로 각각출력하세요.

In [99]:
list_e = [1.2,2.3,3]
array_e1 = np.array(list_e)
print(array_e1,array_e1.dtype,'\n')
array_e2 = array_e1.astype(int)
print(array_e2,array_e2.dtype)

[1.2 2.3 3. ] float64 

[1 2 3] int32


In [100]:
# 배열의 산술 연산
arr = np.array([[1,2,3],[4,5,6]])
arr = np.arange(1,7).reshape(2,3)
print(arr,arr.dtype)

[[1 2 3]
 [4 5 6]] int32


In [101]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [102]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [103]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [104]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [115]:
# 기본 사칙연산
value1 = np.arange(1,10).reshape(3,3)
value2 = np.arange(11,20).reshape(3,3)

print(value1 + value2)
print(np.add(value1,value2),'\n')
print(value1 - value2)
print(np.extract(value1,value2),'\n')
print(value1 * value2)
print(np.multiply(value1,value2),'\n')
print(value1 / value2)
print(np.divide(value2,value2))

[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[12 14 16]
 [18 20 22]
 [24 26 28]] 

[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
[11 12 13 14 15 16 17 18 19] 

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]] 

[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [130]:
arr= np.random.randn(2,2)
arr

array([[-0.36065543,  0.79085122],
       [-0.51081547, -1.15454308]])

In [135]:
arr.mean().round(4)      #round(소수점 반올림)

-0.3088

In [134]:
arr.mean(axis=1)            #axis = 축   ?

array([ 0.21509789, -0.83267927])

In [133]:
arr.mean(axis=0)

array([-0.43573545, -0.18184593])

In [132]:
arr.sum().round(4)

-1.2352

In [131]:
arr.cumprod()    # 누적 곱

array([-0.36065543, -0.28522478,  0.14569723, -0.16821373])

In [136]:
# 인덱싱, 슬리이싱
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [137]:
arr2d[2]

array([7, 8, 9])

In [138]:
arr2d[2][2]

9

In [139]:
arr2d[:,0]                        

array([1, 4, 7])

In [140]:
arr2d[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#arr2d에서 [3,6],[1,2],[4,5]을 출력하세요

In [144]:
arr2d[:,]

array([[3],
       [6],
       [9]])

In [241]:
ar2d = np.arange(1,10).reshape(3,-1)
print(ar2d[:2,2])
print(ar2d[:2,:2])


[3 6]
[[1 2]
 [4 5]]


In [ ]:
# arr2d를 다른 방식으로 출력

In [149]:
print(arr2d[:2:])

[[1 2 3]
 [4 5 6]]


In [152]:
arr2d[[0,1],:]   # 이방식 좋다.

array([[1, 2, 3],
       [4, 5, 6]])

In [153]:
arr = np.arange(30).reshape(5,6)
arr 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
[14,15,16]
[3,9]
[1,7,13]

In [156]:
arr[2][2:5]

array([14, 15, 16])

In [158]:
arr[[0,1],3]

array([3, 9])

In [163]:
arr[[0,1,2],1]

array([ 1,  7, 13])

In [169]:
# 배열을 리스트로 변환
li = arr.tolist()
print(li, type(li))

[[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23], [24, 25, 26, 27, 28, 29]] <class 'list'>


In [173]:
# Boolean indexing        *********매우 중요함************
arr1d = np.arange(1,10)
print(arr1d)
arr3 = arr1d[arr1d > 5]
print(arr3)
print(arr1d > 5)

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[False False False False False  True  True  True  True]


In [ ]:
# arr1d에서 일반 인덱스를 이용해서 6,7,8,9출력

In [176]:
print(arr1d[5:])


[6 7 8 9]


In [ ]:
# 1~14까지 ndarry를 만들어 array_e로 저장하고 (array_e/2)> 5를 만족하는 값을 불린 인덱싱을 출력하세요

In [182]:
array_e = np.arange(1,15)
print(array_e)

arr2d = array_e[(array_e/2)>5]
print(arr2d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[11 12 13 14]


In [187]:
names = np.array(['Bob', 'Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)
print(names, '\n')
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe'] 

[[-1.98521245 -1.66751706 -0.04126002  1.00893821]
 [-0.44399939  1.83932588  1.39663277  1.04254448]
 [-0.10336989  0.60190407  0.88202715  0.11016675]
 [-0.60071727 -0.13559932 -2.18916594  0.56018087]
 [ 0.3128814   0.05875148 -0.23267386 -0.64352974]
 [ 1.3364014   0.1099006   1.60452581  0.12440914]
 [ 1.52724505  0.48919152 -1.20159475  0.21244782]]


In [188]:
names =='Bob'

array([ True, False, False,  True, False, False, False])

In [189]:
data[names =='Bob']

array([[-1.98521245, -1.66751706, -0.04126002,  1.00893821],
       [-0.60071727, -0.13559932, -2.18916594,  0.56018087]])

In [190]:
data[names == 'Bob',2:]

array([[-0.04126002,  1.00893821],
       [-2.18916594,  0.56018087]])

In [192]:
# != 부정
data[names != 'BOb']

array([[-1.98521245, -1.66751706, -0.04126002,  1.00893821],
       [-0.44399939,  1.83932588,  1.39663277,  1.04254448],
       [-0.10336989,  0.60190407,  0.88202715,  0.11016675],
       [-0.60071727, -0.13559932, -2.18916594,  0.56018087],
       [ 0.3128814 ,  0.05875148, -0.23267386, -0.64352974],
       [ 1.3364014 ,  0.1099006 ,  1.60452581,  0.12440914],
       [ 1.52724505,  0.48919152, -1.20159475,  0.21244782]])

In [ ]:
# Bob 이거나 Will인것 출력,(mask 또는 | 이용)



In [205]:
mask = (names == 'Bob') | (names =='Will')
data[(names == 'Bob') | (names =='Will')]   
data[mask]

array([[-1.98521245, -1.66751706, -0.04126002,  1.00893821],
       [-0.10336989,  0.60190407,  0.88202715,  0.11016675],
       [-0.60071727, -0.13559932, -2.18916594,  0.56018087],
       [ 0.3128814 ,  0.05875148, -0.23267386, -0.64352974]])

In [206]:
# 음수를 모두 0으로 처리 방법

In [207]:
data[data<0] = 0
print(data)

[[0.         0.         0.         1.00893821]
 [0.         1.83932588 1.39663277 1.04254448]
 [0.         0.60190407 0.88202715 0.11016675]
 [0.         0.         0.         0.56018087]
 [0.3128814  0.05875148 0.         0.        ]
 [1.3364014  0.1099006  1.60452581 0.12440914]
 [1.52724505 0.48919152 0.         0.21244782]]


In [ ]:
#[과제] 1~100까지 정수에서 3의 배수인 것만을 출력(for, 배열)


In [219]:
arr = np.arange(3,101,3)

arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [217]:
a = list(range(1, 101))

for n in a: 
          if n % 3 ==0:
             print(n)

3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
51
54
57
60
63
66
69
72
75
78
81
84
87
90
93
96
99


In [211]:
#[과제] 1~100까지 정수에서 5의 배수이면서 2의 배수만을 출력 (for , 배열)

In [220]:
arr = np.arange(10,101,10)

arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [218]:
a = list(range(1, 101))

for n in a: 
          if n % 10==0:
             print(n)

10
20
30
40
50
60
70
80
90
100


In [4]:
[i for i in range(1,101) if i%10==0 ]


[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [237]:
#[과제] 표준정규분포로 구성된 5행5열 다차원 배열을 생성하고 함수를 이용하여 평균과 표준편차 구하라
data = np.random.randn(5,5)
print(data)

np.mean(data).round(5)


[[-1.77167497 -0.64995007 -3.15223992  0.60387827  0.48250117]
 [ 0.70563589  0.98601778  0.07723702 -0.44655464 -0.89815846]
 [-0.42480961  2.84523686  0.72854891  0.07156253  0.6653728 ]
 [-0.59584887  0.13855511  0.93318692 -1.34723075  1.22512796]
 [-1.46581622 -1.40609659  0.06042754  0.20742406 -0.47277905]]


-0.11602

In [238]:
np.std(data)

1.173925006581458

In [ ]:
arr1 = np.random.randn(5,5)
print(arr1.mean())
print(arr1.std())


In [5]:
arr1 = np.random.randn(10000,10000)
print(arr1.mean())
print(arr1.std())


0.00013116004579821424
1.0000770329971542


In [ ]:
#[과제] 현재 사용하고 있는 numpy 버전을 출력

In [6]:
print(np.__version__)


1.21.2


In [224]:
!pip install numpy

In [ ]:
#[과제] numpy을  함수의 도움말 기능볼수있는 방법을 수행하여 add 함수의 가이드를 출력

In [8]:
np.info(np.add)



add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [ ]:
# [과제] zeros 함수를 이용해서 아래와 같이 출력
array([0.,0.,0.,1.,0.,0.,0.,0.,0.,])

In [9]:
a = np.arange(10,dtype = float)
b = np.zeros_like(a)
b[4]=1
b


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [10]:
# 선생
n = np.zeros(10)
n[4] = 1
n

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
#[과제]인덱싱을 이용하여 아래 배열을 내림차순으로 정렬하세요
[0,1,2,3,4,5,6,7,8,9]

In [244]:
arr1d = [0,1,2,3,4,5,6,7,8,9]
arr1d.reverse()
print(arr1d)

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [11]:
arr = np.arange(10)
print(arr[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [ ]:
#[과제][1.2.0,0,4,0]dpti zero가 아닌 인덱스를 배열 형태로 출력  

In [1]:
print([i for i in [1, 2, 0, 0, 4, 0] if i != 0])

[1, 2, 4]


In [2]:
print([1, 2, 0, 0, 4, 0][1:])

[2, 0, 0, 4, 0]


In [17]:
# 0이 아닌 인덱스 반환
a = np.array([1,2,0,0,4,0])
np.nonzero(a)


(array([0, 1, 4], dtype=int64),)

In [19]:
# Fancy Indexing
arr = np.empty((8,4))
arr
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [20]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [21]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [23]:
arr = np.arange(32).reshape((8,4))
print(arr,'\n')

arr[[1,5,7,2],[0,3,1,2]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] 



array([ 4, 23, 29, 10])

In [25]:
print(arr[[1,5,7,2]],'\n')
print(arr[[1,5,7,2]][:,[0,3,1,2]])

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]] 

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [27]:
#배열 전치와 축 바꾸기
arr = np.arange(15).reshape(3,5)
print(arr,'\n')
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
