In [38]:
import numpy as np

In [5]:
#randint 랜덤하게 정수를 뽑는다,
arr = np.random.randint(1,10, size=(5,5))  
arr

array([[8, 5, 6, 6, 6],
       [6, 1, 5, 7, 6],
       [8, 3, 7, 5, 9],
       [3, 2, 7, 8, 7],
       [1, 6, 8, 8, 2]])

In [8]:
#전치
arr.T
np.transpose(arr)

array([[9, 9, 1, 7, 9],
       [9, 9, 5, 3, 7],
       [8, 7, 4, 9, 6],
       [8, 3, 5, 1, 8],
       [2, 6, 8, 4, 7]])

In [10]:
# 행렬곱, 내적
np.dot(arr.T, arr)

array([[293, 251, 256, 183, 171],
       [251, 245, 224, 183, 173],
       [256, 224, 246, 162, 168],
       [183, 183, 162, 163, 134],
       [171, 173, 168, 134, 169]])

In [17]:
a = np.arange(6).reshape(2,3)
print(a,'\n')
# 2행 3열을 3행 2열로 
y = np.swapaxes(a, 0,1)   # 0은 2차원(열), 1은 1차원(행)
print(y,'\n')

y = a.T
y = np.transpose(a)
y = np.transpose(a)
print(y)

[[0 1 2]
 [3 4 5]] 

[[0 3]
 [1 4]
 [2 5]] 

[[0 3]
 [1 4]
 [2 5]]


In [ ]:
# 1~100을 아래와 같이 출력하세요
[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>


In [28]:
arr = np.arange(1,101).reshape((10,10))
print(arr,'\n')


[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]] 



In [30]:
arr = np.arange(1,101).reshape(10,10)
arr[[1,3,5,7,9]] = arr[[1,3,5,7,9]][:,[9,8,7,6,5,4,3,2,1,0]]
print(arr)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


In [34]:
# (0,1,2,) = (3차, 2차, 1차)
# 3차원과 2차원을 바꾸는 경우 : (1,2,3) ->(2,1,3)
a= np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')

y = np.transpose(a,(1,0,2))   #(2차,3차,1차)
print(y,y.shape,'\n')

[[[0 1 2]
  [3 4 5]]] (1, 2, 3) 

[[[0 1 2]]

 [[3 4 5]]] (2, 1, 3) 



In [40]:
# (1,2,3) ->(2,3,1)
a= np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')

y = np.transpose(a,(1,2,0)) 
print(y,y.shape,'\n')

[[[0 1 2]
  [3 4 5]]] (1, 2, 3) 

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1) 



In [43]:
#[과제] 아래 배열에서 3차원과 2차원을 변경하여 출력(shape)
arr = np.arange(16).reshape(2,2,4)
print(arr,arr.shape,'\n')


y = np.transpose(a,(2,0,1))
print(y,y.shape,'\n')

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 

[[[0 3]]

 [[1 4]]

 [[2 5]]] (3, 1, 2) 



In [ ]:
[과제] 상기 과제의 arr에서 2차원과 1차원을 변경하여 출력하세요

In [45]:
# 나머지를 구할 경우 사용하는 함수  (mod, remainder)
value1 = np.array([15,30,45])
value2 = np.array([2,7,9])
print(np.mod(value1,value2))
print(np.remainder(value1,value2))

[1 2 0]
[1 2 0]


In [49]:
# 각 수의 역수를 구해주는 함수   (reciprocal)
value = np.array([0.85,1.85,1,100])
print(np.reciprocal(value),'\n')

vlaue1 = np.array([100],dtype = int)
print(value1,'\n')
print(np.reciprocal(value1, dtype=float))

[1.17647059 0.54054054 1.         0.01      ] 

[15 30 45] 

[0.06666667 0.03333333 0.02222222]


In [50]:
# 승수의 결과 값을 표시해주는 함수
value1 = np.array([2,10,15])
value2 = np.array([1,2,3])

print(np.power(value1,2),'\n')
print(np.power(value1,value2))

[  4 100 225] 

[   2  100 3375]


In [53]:
arr = np.random.randn(10)
# print(arr.mean(),'\n')
# print(arr.std())

-0.29369593897057633 

1.0754132278399056


In [54]:
# 양수인 원소의 개수   
(arr > 0).sum()

4

In [55]:
#하나 이상의 값이 True인지 검사
bools = np.array([False,False,True,True])
bools.any()

True

In [56]:
# 모든 원소가 True인지 검사
bools.all()

False

In [58]:
# 삼항식의 벡터화 버전
arr = np.random.randn(4,4)
print(arr,'\n')
np.where(arr > 0, 2, -2)

[[-0.88067366  0.24459866  2.54408943 -0.55511661]
 [-0.6279777   1.93901159 -0.73087764 -0.49476424]
 [-1.33192268  1.10651961  1.32449631 -0.11953121]
 [ 0.25698587  0.71090106  1.07226634 -1.56083498]] 



array([[-2,  2,  2, -2],
       [-2,  2, -2, -2],
       [-2,  2,  2, -2],
       [ 2,  2,  2, -2]])

In [59]:
# arr의 모든 양수를 2로 바꿀 경우
np.where(arr > 0, 2, arr)

array([[-0.88067366,  2.        ,  2.        , -0.55511661],
       [-0.6279777 ,  2.        , -0.73087764, -0.49476424],
       [-1.33192268,  2.        ,  2.        , -0.11953121],
       [ 2.        ,  2.        ,  2.        , -1.56083498]])

In [61]:
# 두 개의 1차원 배열을 받아서 가능한 모든 (x,y)짝을 만들수있는 2차원 배열 2개 반환
x = np.arange(1,4)
y = np.arange(1,4)
xs,ys = np.meshgrid(x,y)
print(xs,'\n')
print(ys)

[[1 2 3]
 [1 2 3]
 [1 2 3]] 

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [69]:
# np.sort()
np.random.seed(0)    #(숫자 고정)
arr = np.random.randint(1,100,size =10)
print(arr,'\n')
print(np.sort(arr),'\n')
print(arr)

[45 48 65 68 68 10 84 22 37 88] 

[10 22 37 45 48 65 68 68 84 88] 

[45 48 65 68 68 10 84 22 37 88]


In [70]:
sorted = np.sort(arr)
print(sorted)

[10 22 37 45 48 65 68 68 84 88]


In [73]:
# 행렬이 2차원 이상일 떄 axis 축 값 설정을 통해 행,열 방향으로 정렬 수행
arr2d = np.array([[8,12],[7,1]])
print(arr2d,'\n')
sort_ar2d_axis0 = np.sort(arr2d, axis=0)
print(sort_ar2d_axis0,'\n')
sort_ar2d_axis1 = np.sort(arr2d, axis=1)
print(sort_ar2d_axis1)

[[ 8 12]
 [ 7  1]] 

[[ 7  1]
 [ 8 12]] 

[[ 8 12]
 [ 1  7]]


In [39]:
# ndarray.sort() : 원본 반영   (배열.sort)
np.random.seed(0)
arr = np.random.randint(1,10,size=10)
# arr = np.random.randn(6)
print(arr,'\n')
arr.sort()     #원본 반영
print(arr)

[6 1 4 4 8 4 6 3 5 8] 

[1 3 4 4 4 5 6 6 8 8]


In [92]:
# 다차원 배열의 정렬은 sort 메소드에 넘긴 축에 따라 1차원 부분을 정렬
#열방향 정렬,, default
np.random.seed(0)
arr = np.random.randint(1,10,size=(5,3))
print(arr,'\n')
arr.sort()
print(arr)

[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]
 [9 2 7]] 

[[1 4 6]
 [4 4 8]
 [3 5 6]
 [7 8 9]
 [2 7 9]]


In [91]:
# 행방향 정렬
np.random.seed(0)
arr = np.random.randint(1,10,size=(5,3))
print(arr,'\n')
arr.sort(0)
print(arr)

[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]
 [9 2 7]] 

[[4 1 4]
 [6 2 4]
 [6 3 5]
 [8 7 7]
 [9 8 9]]


In [94]:
# 정렬된 행렬의 인덱스 반환 : 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(org_array)
print(type(sort_indices))
sort_indices

[3 1 9 5]
<class 'numpy.ndarray'>


array([1, 0, 3, 2], dtype=int64)

In [40]:
# 배열에서 정렬한 후 50%에 해당하는  원소만 출력
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.5*len(large_arr))]

-0.027971183469780222

In [100]:
# 배열 집합 연산
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [9]:
import numpy as np
names = np.array(['Bob','Joe','Will','Joe','Joe'])
sorted(set(names))

['Bob', 'Joe', 'Will']

In [8]:
# 첫 번째 배열의 원소가 두번째 배열의 원소를 포함하는지 알려주는 불리언 배열을 변환
values = np.array([6,0,0,3,2,5,6])
np.in1d(values, [2,3,6])

array([ True, False, False,  True,  True, False,  True])

In [11]:
# 배열 데이터의 입출력
# np.save , np.load는 바이너리 형식  .npy 파일로 저장

arr = np.arange(10)
np.save('some_array',arr)

In [12]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# np.savez : 여러개의 배열을  압축된 형식으로 저장
np.savez('array_archive.npz',a= arr, b=arr)

In [15]:
arch = np.load('array_archive.npz')
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Q. 인덱싱을 사용하여 [1 0 1 0 1 0 1 0]10]을 출력하세요
a = np.ones(10,dtype=int)
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [32]:
a = np.ones(10).astype(int)
a[[1,3,5,7,9]] = 0
print(a)


[1 0 1 0 1 0 1 0 1 0]


In [ ]:
a = np.arange(10)에서 [6,7,8,9] 출력

In [21]:
a = np.arange(10)
print(a)
np.where( a > 5)

[0 1 2 3 4 5 6 7 8 9]


(array([6, 7, 8, 9], dtype=int64),)

In [24]:
# 친구 풀이
a = np.arange(10)
b = a>5
print(a[b])


[6 7 8 9]


In [ ]:
# a에서 최대값, 최솟값의 인덱스 출력

In [41]:
# 친구풀이

a = np.arange(10)
print(f'최댓값: {np. argmax(a)}\n최솟값: {np.argmin(a)}')


최댓값: 9
최솟값: 0


In [25]:
print(max(a), min(a))


9 0


In [23]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# a 에서 인덱스 배열을 역순으로 출력하세요 

In [27]:
np.argsort(a)[::-1]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int64)

In [ ]:
# Q.np.ones((10,10))을 아래와 같이 출력하세요
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [42]:
b=np.ones((10,10))
b[1:9,1:9]=0
b


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# [도전] np.arrange(4)을 이용해서 아래와 같이 출력하세요
array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])


In [ ]:
#[도전과제] np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요

In [ ]:
#[과제] np.ones((5,5))을 아래와 같이 출력하세요.
array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [18]:
#이상태에서 바깥에 0으로 둘러싸이게 만드는거
np.ones((5,5))
x = np.ones((5,5))
print(x)

np.pad(x,(2,2),mode='constant', constant_values=0)  #pad(특정 배열을  0으로 채울때 x(행,열) values=숫자)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
# [과제] np.zeros((8,8,))을 이용해서 아래와 같이 출력하세여(인덱싱,tile 함수) (tile = 복붙 함수)
array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])


NameError: name 'array' is not defined

In [47]:
a=np.zeros((8,8,))

a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

[파이썬 random 함수]

In [4]:
import random
print(random.random(),'\n') # 0.0 <= x <1.0 사이
print(random.randint(1,10),'\n')  #1에서 10사이의정수중 난수 값 리턴
print(random.uniform(10,20),'\n') #min , max사이  float 리턴 
print(random.randrange(10), '\n') # 지정 범위 int 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
print(random.sample(li,3),'\n')  # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li)  #리스트 요소를 다시 섞어서 리턴
print(li)

0.9783462406766948 

9 

18.422150242862834 

1 

5 

[2, 1, 3] 

[5, 3, 1, 4, 2]


.[numpt random 함수]
- np.random.seed   # seed를 통한 난수 생성 
- np.random.randint  #균일분포의 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn: 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle: 기존의 데이터의 순서 바꾸기
- np.random.choice: 기존 데이터에서 sampling


In [16]:

print(np.random.randint(6),'\n') # 0~5까지 정수인 난수 1개
print(np.random.randint(1,20),'\n')  # 1~19까지 정수인  난수 1개
print(np.random.randint(10,size=10),'\n') # 0~9까지  정수인 난수10개
print(np.random.randint(10,20, size=10),'\n') #10~19까지의 정수인 난수 10개
print(np.random.randint(10,20, size=(3,5)))  # 10~19까지의 정수인 난수로 3행 5열  배열 생성

5 

6 

[1 0 5 2 3 3 1 6 0 3] 

[12 13 15 15 13 13 12 16 18 12] 

[[13 10 14 16 16]
 [14 10 13 12 11]
 [14 18 17 14 12]]


In [17]:
r = np.random.rand(6)  # 0~1사이의 균일 분포
print(r,'\n')
r.mean()

[0.33737597 0.3712621  0.78208038 0.63408325 0.55826239 0.96410616] 



0.6078617069425943

In [18]:
# 표준 정규분포
r = np.random.randn(6)
r.mean()

-0.5691663583309564

In [19]:
list = np.arange(1,6)
print(list,'\n')
np.random.shuffle(list)
list

[1 2 3 4 5] 



array([1, 3, 5, 4, 2])

In [20]:
np.random.choice(list)

5

In [21]:
a = np.array([11,11,3,3,2,2,2,7])
index,count = np.unique(a,return_counts=True)
print(index)
print(count)

[ 2  3  7 11]
[3 2 1 2]


In [22]:
np.random.uniform(1.0,2.0,10)

array([1.00651026, 1.21449366, 1.03759168, 1.83908886, 1.41527912,
       1.43912916, 1.72648091, 1.24934409, 1.22003408, 1.38285255])

In [26]:
print(np.random.uniform(0,1,(2,3)))

[[0.7040838  0.98842712 0.88534981]
 [0.89163332 0.74787425 0.84767072]]


In [24]:
#0~1 사이의 난수 실수값으로 행렬 생성
# uniform 함수의 최소값, 최댓값을 각각 0,1로 지정한것과 같다.
np.random.random_sample((2,3))

array([[0.79688385, 0.88332909, 0.29115615],
       [0.41124188, 0.46995509, 0.48567791]])

In [27]:
! pip install pandas

In [75]:
ar = np.random.rand(4,8)
ar

array([[0.71919026, 0.2976462 , 0.31135161, 0.39276994, 0.30159018,
        0.6155525 , 0.1649588 , 0.43723524],
       [0.95534268, 0.65464163, 0.5803407 , 0.67576877, 0.67731991,
        0.04621297, 0.79135956, 0.34299148],
       [0.4452796 , 0.14274233, 0.52657235, 0.61144643, 0.06991683,
        0.64688754, 0.60593281, 0.62561214],
       [0.97671053, 0.07188293, 0.66581476, 0.6127399 , 0.43434702,
        0.02218112, 0.93718019, 0.78329609]])

In [76]:
# 배열을 데이터프레임으로 변환
import pandas as pd
df = pd.DataFrame(ar)
df

0         1         2         3         4         5         6  \
0  0.719190  0.297646  0.311352  0.392770  0.301590  0.615553  0.164959   
1  0.955343  0.654642  0.580341  0.675769  0.677320  0.046213  0.791360   
2  0.445280  0.142742  0.526572  0.611446  0.069917  0.646888  0.605933   
3  0.976711  0.071883  0.665815  0.612740  0.434347  0.022181  0.937180   

          7  
0  0.437235  
1  0.342991  
2  0.625612  
3  0.783296

In [77]:
columns = ['id', 'gender','age','region','product','price','qty','time']
index = [np.arange(4)]
df = pd.DataFrame(ar,index,columns=columns)
df


id    gender       age    region   product     price       qty  \
0  0.719190  0.297646  0.311352  0.392770  0.301590  0.615553  0.164959   
1  0.955343  0.654642  0.580341  0.675769  0.677320  0.046213  0.791360   
2  0.445280  0.142742  0.526572  0.611446  0.069917  0.646888  0.605933   
3  0.976711  0.071883  0.665815  0.612740  0.434347  0.022181  0.937180   

       time  
0  0.437235  
1  0.342991  
2  0.625612  
3  0.783296

In [ ]:
idm gender age컬럼에 대하여 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 df를 구하세요

In [80]:
# 선생 풀이
ar = np.zeros((4,3))
columns = ['id', 'gender', 'age']
index = [np.arange(4)]
df = pd.DataFrame(ar,index,columns=columns)
df.id = np.array([1,2,3,4]) #arange(1,5)
df.gender = np.array([0,1,0,1])  #
df.age = np.array([20,30,40,50])
df

id  gender  age
0   1       0   20
1   2       1   30
2   3       0   40
3   4       1   50

In [71]:
ID = np.random.randint(1000,10000,3)
gen = np.random.choice(['M','F'],3)
age = np.random.randint(10,40,3)

data = np.array([ID,gen,age]).reshape(3,3).transpose()
df=pd.DataFrame(data,np.arange(1,4),['ID','Gender','Age'])
df


ID Gender Age
1  8582      M  16
2  9618      M  37
3  1948      F  38

In [85]:
ID = np.random.randint(1000,10000,3)
gen = np.random.choice(['M','F'],3)
age = np.random.randint(10,40,3)

data = np.array([ID,gen,age]).reshape(3,3).transpose()
df=pd.DataFrame(data,np.arange(1,4),['ID','Gender','Age'])
df

h = np.zeros((3, 10))
id_ = np.random.randint(1, 1000, size = (1, 10))
gender = np.random.randint(2, size = (1, 10))
age = np.random.randint(0, 120, size = (1, 10))

h[0] = id_
h[1] = gender
h[2] = age

h = np.transpose(h)

columns = ['id', 'gender', 'age']
index = np.arange(1, 11)
df = pd.DataFrame(h, index, columns = columns)

df


id  gender   age
1   338.0     1.0  82.0
2   252.0     0.0  87.0
3   111.0     1.0  31.0
4   858.0     1.0  40.0
5   486.0     0.0  93.0
6   693.0     0.0  64.0
7   668.0     1.0  42.0
8   297.0     0.0  21.0
9   845.0     0.0  72.0
10  808.0     0.0  70.0

In [ ]:
#[과제]아래 가이드에 따라서 고객구매 데이터를 생성하고 데이터프레임으로 변환하여 출력(관측1000개)
id : 1~1000번 일련번호
gender : 0,1 정수 난수 생성
age: 0~80사이 정수 난수 생성
region: 1~10 사이 정수 난수 생성
product_19: 제품코드 11111~99999사이 실수 난수 생성
product_20: 제품코드 11111~99999사이 실수 난수 생성
price_19 : 1000~50000사이 실수 난수 생성
price_20 : 1000~50000사이 실수 난수 생성
quantity_19:1~100 사이 정수 난수 생성
quantity_20:1~100 사이 정수 난수 생성
time_19 : 1~24사이 정수 난수 생성
time_20 : 1~24사이 정수 난수 생성
amount_19: price_19*quantity_19
amount_20: price_20*quantity_20
sales: 19년 대비 20년 구매 금액이 증가면 1, 감소면 0
    

In [86]:
ar = np.zeros((1000,15))
columns = ['id', 'gender', 'age','region','product_19','product_20','prcie_19','price_20','quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales']
index = [np.arange(1000)]
df = pd.DataFrame(ar,index,columns=columns)
df.id = np.arange(1,1000) 
np.random.seed(0)
df.gender =  np.random.randint(2,size=5)
df.age = np.random.randint(80,size=80)
df.region:np.random.randint(1,10, size=10) 
df.product_19:np.arange(11111,99999)
df.product_20:np.arange(11111,99999)
df.price_19:np.uniform(1000,50000)
df.price_20:np.uniform(1000,50000)
df.quantity_19:np.random.randint(1,100)
df.quantity_20:np.random.randint(1,100)
df.time_19:np.random.randint(1,24)
df.time_20:np.random.randint(1,24)
df.amount_19:print(price_19*quantity_19)
df.amount_20:print(price_20*quantity_20)
df.sales:

ValueError: Length of values (99) does not match length of index (5)